# Default values for canary-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName:   logicapp
namespace: logicapp-prod

replicaCount: 3

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

image:
  repository_imageappprobe: tpayne666/samples
  repository_imagecmdprobe: alpine
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  cmd: '["/bin/sh", "-c"]'

readinessProbeApp:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

livenessProbeApp:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20

readinessProbeCmd: {}

livenessProbeCmd:
      exec:
        command:
          - cat
          - /tmp/test
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 2