apiVersion: v1
entries:
  database-deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-04T11:47:20.589262Z"
    description: A Helm chart for Kubernetes
    digest: 41a550552f907ef078adb58af348a3713f71f0e5c78cd2ad108e53a52cd56181
    name: database-deployment
    type: application
    urls:
    - database-deployment-0.1.0.tgz
    version: 0.1.0
generated: "2022-03-04T11:47:20.588175Z"
