apiVersion: v1
entries:
  database-deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-04T12:57:32.231386Z"
    description: A Helm chart for Kubernetes
    digest: 138ac0e35eaf7f441d8dde4bd2a201b95ac31f1457a489eb76ee64ca788e7259
    name: database-deployment
    type: application
    urls:
    - database-deployment-0.1.0.tgz
    version: 0.1.0
generated: "2022-03-04T12:57:31.968203Z"
