# Now let's create a deployment in that namespace that contains 2 versions of the same app...
---
apiVersion: v1
kind: Pod
metadata:
  namespace: db-frontend
  name: postgres-client
spec:
  containers:
  - name: pgclient
    image: tpayne666/alpine-pgclient:latest
    imagePullPolicy: Always