apiVersion: v1
kind: Service
metadata:
  name: postgres-svr
  namespace: db-backend
spec:
  selector:
    app: postgres-container
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
