wscs-deployment:
  image:
    tag: "latest"
  service:
    type: ClusterIP
wscs-b-deployment:
  image:
    tag: "latest"
  service:
    type: ClusterIP
wsnodejs-deployment:
  image:
    tag: "master"
  service:
    type: ClusterIP
wsnodejs-b-deployment:
  image:
    tag: "master"
  service:
    type: ClusterIP
jenkinscd-framework-deployment:
  image:
    tag: "latest"
  service:
    type: ClusterIP
