apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-dev
  labels:
    app: pipeline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: pipeline
  source:
    repoURL: https://github.com/tpayne/kubernetes-examples
    targetRevision: main
    path: ./YAML/Argocd/helm/dev  # Directory that contains the child apps
    helm:
      parameters:
        - name: buildID
          value: argocd
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true