# Config types for maps...
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: monitor
data:
  # File properties...
  kubernetes.conf: |
      <match fluent.**>
        @type file
        path /var/log/sys-fluentd.log
        time_slice_format %Y%m%d
        time_slice_wait 10m
        time_format %Y%m%dT%H%M%S%z
        compress gzip
      </match>

---
# Monitoring exporter...
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  namespace: monitor
  labels:
    name: node-monitor
    env: prod
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      name: node-monitor
  template:
    metadata:
      labels:
        name: node-monitor
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "9100"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: fluentd-esearch
          image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
          - name: config-volume
            mountPath: /etc/fluent/config.d/kubernetes.conf
            subPath: kubernetes.conf
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
        - name: node-monitor
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          image: prom/node-exporter:v0.15.2
          args:
            - --path.procfs
            - /host/proc
            - --path.sysfs
            - /host/sys
            - --collector.filesystem.ignored-mount-points
            - '"^/(sys|proc|dev|host|etc)($|/)"'
            - --collector.textfile.directory
            - /logs
          volumeMounts:
            - name: dev
              mountPath: /host/dev
            - name: proc
              mountPath: /host/proc
            - name: sys
              mountPath: /host/sys
            - name: rootfs
              mountPath: /rootfs
            - name: logs
              mountPath: /logs
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-conf
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: proc
          hostPath:
            path: /proc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: logs
          hostPath:
            path: /logs
        - name: rootfs
          hostPath:
            path: /
