apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localstorage
  namespace: {{ .Values.namespaces.benamespace }}
  labels:
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: True
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "standard3tier-deployment.fullname" . }}-dbstorage
  namespace: {{ .Values.namespaces.benamespace }}
  labels:
    type: local
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
spec:
  storageClassName: localstorage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres01"
    type: DirectoryOrCreate
