apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaces.benamespace }}
  name: {{ include "standard3tier-deployment.fullname" . }}-dbsvr
  labels:
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "standard3tier-deployment.fullname" . }}-dbclient
  ports:
    - name: {{ include "standard3tier-deployment.fullname" . }}-dbsvr
      port: {{ .Values.service.dbport }}
      protocol: TCP
      targetPort: {{ .Values.service.dbport }}
  type: {{ .Values.service.type }}
