apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespaces.benamespace }}
  name: {{ include "standard3tier-deployment.fullname" . }}-dbdeploy
  labels:
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "standard3tier-deployment.fullname" . }}-dbsvr
  selector:
    matchLabels:
      {{- include "standard3tier-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "standard3tier-deployment.selectorLabels" . | nindent 8 }}
        app: {{ include "standard3tier-deployment.fullname" . }}-dbcontainer
        env: prod
    spec:
      containers:
      - name: {{ include "standard3tier-deployment.fullname" . }}-dbcontainer
        image: {{ .Values.image.dbsrvImage }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.dbport }}
        envFrom:
          - configMapRef:
              name: {{ include "standard3tier-deployment.fullname" . }}-dbconfig
        volumeMounts:
          - name: {{ include "standard3tier-deployment.fullname" . }}-dbstorage
            mountPath: /var/lib/postgresql
        resources: # These will need much better tuning...
          {{- toYaml .Values.backend.dbServerResources | nindent 12 }}
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: {{ include "standard3tier-deployment.fullname" . }}-dbstorage
      spec:
        storageClassName: localstorage
        accessModes: ["ReadWriteMany"]
        resources:
         requests:
          storage: 5Gi
        selector:
         matchLabels:
          type: local