apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Values.namespaces.benamespace }}
  name: {{ include "standard3tier-deployment.fullname" . }}-dbclient
  labels:
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
spec:
  containers:
  - name: {{ include "standard3tier-deployment.fullname" . }}-dbclient
    image: "{{ .Values.image.dbImage }}:{{ .Values.image.dbTag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
