apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitops-deploy
spec:
  eventBusName: monitoredrepo-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-reposrc:
      events:
        - push
      repositories:
        - owner: tpayne
          names:
            - lang-examples
            - kubernetes-examples
      webhook:
        port: "80"
        method: POST
        endpoint: >-
          /webhooks/gitops-deploy/github-reposrc
        # You will need to customise this as appropriate
        url: https://argorestapi.ukwest.cloudapp.azure.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
