# Release stack to deploy on target
decision-service-a:
  containerImage:
    tag: "1.14.2"
github-service:
  containerImage:
    tag: "22dca71"
wsnodejs-deployment:
  containerImage:
    tag: "latest"
wscs-deployment:
  containerImage:
    tag: "latest"