apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pipeline-qa
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Deployment of pipeline-qa

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Permit applications to deploy to any namespace in any cluster
  destinations:
  - namespace: '*'
    server: '*'

  # Permit cluster-scoped resources to be created
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
