---
# Lets first create an application namespace to use...
apiVersion: v1
kind: Namespace
metadata:
  name: logicapp-prod
---
apiVersion: batch/v1beta1 
kind: CronJob 
metadata: 
  name: cronjob-sample 
  namespace: logicapp-prod
spec: 
  schedule: "*/5 * * * *" # Run every 5 mins... 
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers: 
          - name: cron-example 
            image: alpine
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "AppRun:"; date; env
          restartPolicy: OnFailure