decision-service-a:
  applicationName: decision-service-dev
  containerImage:
    repository: nginx
  service:
    type: NodePort
decision-service-b:
  applicationName: decision-service-test
  containerImage:
    repository: nginx
  service:
    type: NodePort