apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database-deployment.fullname" . }}-dbconfig
  namespace: {{ .Values.namespaces.benamespace }}
  labels:
    {{- include "database-deployment.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.dbMap | nindent 2 }}





