# permissions for end users to view ghactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubactions-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crdoperators
    app.kubernetes.io/part-of: crdoperators
    app.kubernetes.io/managed-by: kustomize
  name: githubactions-viewer-role
rules:
- apiGroups:
  - github.actions.io.github.actions.io
  resources:
  - ghactions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.actions.io.github.actions.io
  resources:
  - ghactions/status
  verbs:
  - get
