apiVersion: v1
entries:
  wscs-deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-27T14:58:12.164365+01:00"
    description: A Helm chart for Kubernetes
    digest: 0bf1d0dfe8e8166da814a6fd62f7a67337e80ad6d104a5a65e800f833ef95e73
    name: wscs-deployment
    type: application
    urls:
    - wscs-deployment-0.1.0.tgz
    version: 0.1.0
generated: "2022-03-27T14:58:12.162878+01:00"
