apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespaces.mnnamespace }}
  name: fluentd-conf
  labels:
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
data:
  {{ .Files.Get "files/monitorConfig.txt" | indent 2 }}