steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
    dir: Maven/web8k-example
    id: Test build
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/samples", "."]
    dir: Maven/web8k-example
    id: Image Build
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/samples"]
    dir: Maven/web8k-example
    id: Image Push to repo
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gitops/gcp/deploy-gcp.yaml
    - --image=gcr.io/$PROJECT_ID/samples:latest
    - --location=$_GKE_LOCATION
    - --cluster=$_GKE_CLUSTER
    id: Deploy image cluster
images: ["gcr.io/$PROJECT_ID/samples"]
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GKE_LOCATION: europe-west1-d
  _GKE_CLUSTER: gitops

