  steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
    dir: Maven/web8k-example
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
    dir: Maven/web8k-example
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/samples", "--build-arg=JAR_FILE=target/web8k-example-1.0-SNAPSHOT.jar", "."]
    dir: Maven/web8k-example
images: ["gcr.io/$PROJECT_ID/samples"]
