steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
    dir: Maven/web8k-example
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/samples", "."]
    dir: Maven/web8k-example
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/samples"]
    dir: Maven/web8k-example
images: ["gcr.io/$PROJECT_ID/samples"]
