{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespaces.mnnamespace }}
  name: {{ include "standard3tier-deployment.serviceAccountName" . }}
  labels:
    {{- include "standard3tier-deployment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
