apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - db-backend/db-storage.yaml
  - db-backend/db-config.yaml
  - db-backend/postgres-dbservice.yaml
  - db-backend/postgres-dbstateful.yaml
  - db-backend/pgclient-deploy.yaml
  - frontend/deploy.yaml
  - frontend/lb-service.yaml
  - monitor/roles.yaml
  - monitor/daemonset-monitor.yaml



