# Create a service for the deployment
apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: frontend-svr
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: frontend-deployment
