apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cd-build-prod-
spec:
  synchronization:
    mutex:
      name:  lockforexec-prod
  arguments:
    parameters:
      - name: ARGOCD_APP
        value: pipeline-prod
      - name: ARGOCD_SERVER
        value: argocd-server
      - name: REPO
        value: https://github.com/tpayne/kubernetes-examples.git
      - name: REVISION
        value: 'main'
      - name: GIT_TOKEN_SECRET
        value: 'github-token'
      - name: PROMOTION_TYPE
        value: 'environment'
      - name: TENANT_NAME
        value: ''
        default: ''
      - name: ENVIRONMENT
        value: 'prod'
      - name: PROMOTE_TO
        value: 'nil'
      - name: COMMAND_OPTS
        value: ''
        default: ''
  workflowTemplateRef:
    name: cd-promote-prod
