---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db-backend
  labels:
    app: postgres-db
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data/
  POSTGRES_PASSWORD: password
---
# Lets create a very simple secret...
# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-config-pwd
#   namespace: db-backend
#   labels:
#     app: postgres-db
# data:
#   POSTGRES_PASSWORD: password




