# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

namespace: "logicapp"
image:
  repository: tpayne666/samples
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"

service:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
