apiVersion: v1
kind: Service
metadata:
  name: {{ include "wscs-b-deployment.fullname" . }}
  labels:
    {{- include "wscs-b-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "wscs-b-deployment.selectorLabels" . | nindent 4 }}
