trigger:
  name: github_trigger
  identifier: github_trigger
  enabled: true
  encryptedWebhookSecretIdentifier: PATTOKEN
  description: Execute trigger based on GH
  tags: {}
  orgIdentifier: default
  stagesToExecute: []
  projectIdentifier: default_project
  pipelineIdentifier: sample_pipeline
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: githubconnector
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: changedFiles
              operator: Contains
              value: gitops/Argocd/examples/simple/helm/dev/
            - key: targetBranch
              operator: In
              value: main
          headerConditions: []
          repoName: https://github.com/tpayne/kubernetes-examples.git
          actions: []
  inputYaml: |
    pipeline:
      identifier: sample_pipeline
      stages:
        - stage:
            identifier: sample_stage
            type: Custom
            spec:
              execution:
                steps:
                  - stepGroup:
                      identifier: use_step_group
                      template:
                        templateInputs:
                          steps:
                            - step:
                                identifier: Clone_Code
                                type: ShellScript
                                spec:
                                  outputVariables:
                                    - name: status
                                      type: String
                                      value: ""
