apiVersion: v1
entries:
  wscs-b-deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-11T10:03:41.342463+01:00"
    description: A Helm chart for Kubernetes
    digest: 191f8659f5405e32178c734a433e0a5503429da44bf5928fbe68a71a336b85e1
    name: wscs-b-deployment
    type: application
    urls:
    - wscs-b-deployment-0.1.0.tgz
    version: 0.1.0
  wscs-deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-11T10:03:41.343518+01:00"
    description: A Helm chart for Kubernetes
    digest: 63d2b8078580e8515120f5e5bc0cec4d322344a4336cf44edc17fe552f2ffe4c
    name: wscs-deployment
    type: application
    urls:
    - wscs-deployment-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-11T10:03:41.340506+01:00"
