apiVersion: v1
entries:
  wscs-b-deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-11T10:25:11.206026+01:00"
    description: A Helm chart for Kubernetes
    digest: a5e58be5a4c96d42051a658f71429a6df62548bf4613ef3defef614f9bd545ee
    name: wscs-b-deployment
    type: application
    urls:
    - wscs-b-deployment-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-11T10:25:11.204372+01:00"
