# Default values for canary-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName:   logicapp
namespace: logicapp-prod
replicaCount: 3
replicaCountCanary: 1

image:
  repository: tpayne666/samples
  canaryRepository: tpayne666/samples
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"
  canaryTag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80


